name: Add issues to project
on:
  issues:
    types: opened
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add new issues to project column 'Todo'
      uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/orgs/ds4owd-001/projects/1/
        github-token: ${{ secrets.DS4OWD_PROJECT }}

